"""empty message

Revision ID: 777058764eae
Revises: 461e55e3ae4b
Create Date: 2020-12-19 21:48:04.113329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '777058764eae'
down_revision = '461e55e3ae4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('upcoming_show', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'upcoming_show')
    # ### end Alembic commands ###
