"""empty message

Revision ID: 7e638e6638e0
Revises: 777058764eae
Create Date: 2020-12-21 15:43:32.666616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e638e6638e0'
down_revision = '777058764eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'upcoming_show')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('upcoming_show', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
